scrub: scrub.o  
	g++ scrub.o -o scrub
scrub.o: scrub.cpp
	g++ -c -std=c++11 scrub.cpp



clean:
	rm *o 

normal: normal.o
	g++ normal.o -o normal

normal.o: normal.cpp
	g++ -c -std=c++11 normal.cpp


